apiVersion: apps/v1
kind: Deployment
metadata:
  name: task1-get-image-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1-app
  template:
    metadata:
      labels:
        app: task1-app
    spec:
      containers:
      - name: task1-container
        image: gcr.io/ac295-data-science-289118/task1:frontend
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          valueFrom: 
              configMapKeyRef: 
                  name: webappdb-configmap  #
                  key: database_host  
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
    name: webapp-task1-service  
spec:
    selector:  
        app: task1-app
    type: LoadBalancer  #We want this exposed to the outside world
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
        nodePort: 30000